[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
solc_version    = '0.8.15'       # Override for the solc version (setting this ignores `auto_detect_solc`)
optimizer       = true           # Enable or disable the solc optimizer
optimizer_runs  = 200            # The number of optimizer runs
# verbosity       = 3              # The verbosity of tests

# See more config options https://github.com/foundry-rs/foundry/tree/master/config