[profile.default]
src = 'contracts/solady'
out = 'out'
libs = ['lib']
solc_version    = '0.8.15'       # Override for the solc version (setting this ignores `auto_detect_solc`)
optimizer       = true           # Enable or disable the solc optimizer
optimizer_runs  = 200            # The number of optimizer runs
# verbosity       = 3              # The verbosity of tests
fs_permissions = [{ access = "read", path = "./"}]
# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[rpc_endpoints]
mumbai = "https://rpc.ankr.com/polygon_mumbai"


[etherscan]
polygon_mumbai = { key = "${ETHERSCAN_MAINNET_KEY}" }